---
blank_issues_enabled: true
contact_links:
  - name: Ask a question or get support on dat Slack
    url: https://join.slack.com/t/dlthub-community/shared_invite/zt-1slox199h-HAE7EQoXmstkP_bTqal65g
    about: Need help or support? Join our dat community on Slack and get assistance.